# Generated by Django 4.1.5 on 2024-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
