# Generated by Django 4.1.5 on 2024-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='a_assets',
        ),
    ]
