# Generated by Django 4.1.5 on 2024-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
