# Generated by Django 4.1.5 on 2024-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gmt', models.DateTimeField()),
            ],
            options={
                'db_table': 'a_asset_prices',
            },
        ),
        migrations.CreateModel(
            name='DailyAssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.PositiveBigIntegerField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'a_daily_asset_info',
            },
        ),
    ]
