# Generated by Django 4.1.5 on 2024-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetprice_dailyassetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='market_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyassetinfo',
            unique_together={('asset_id', 'date')},
        ),
    ]
