# Generated by Django 4.1.5 on 2024-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_market_id_alter_dailyassetinfo_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='country',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='country_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='type_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
