# Generated by Django 4.1.5 on 2024-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_asset_country_remove_asset_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'g_asset_types',
            },
        ),
    ]
