# Generated by Django 4.1.5 on 2024-12-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assettype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assettype',
            table='a_asset_types',
        ),
    ]
