# Generated by Django 4.1.5 on 2024-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_assettype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyassetinfo',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
