# Generated by Django 4.1.5 on 2024-12-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assettype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
